import './globals.css';
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const getMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-toolpad-color-scheme="dark">
      <body
        className={`${getMontserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
