import './globals.css';
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { SessionProvider } from './session-provider';
import { getSession } from '@/lib/session';

const getMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()

  return (
    <html lang="en" data-toolpad-color-scheme="dark">
      <body
        className={`${getMontserrat.variable} antialiased`}
      >
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
